"""Add sales table

Revision ID: a2c585c18eb6
Revises: e11eecb9a321
Create Date: 2023-10-01 23:59:46.889086

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2c585c18eb6"
down_revision: Union[str, None] = "e11eecb9a321"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sale",
        sa.Column("quantity_sold", sa.Integer(), nullable=False),
        sa.Column("total_bill", sa.Integer(), nullable=False),
        sa.Column("item_sold_at", sa.Integer(), nullable=False),
        sa.Column("sales_date", sa.Date(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sale_sales_date"), "sale", ["sales_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sale_sales_date"), table_name="sale")
    op.drop_table("sale")
    # ### end Alembic commands ###
