"""Add price to product table

Revision ID: e11eecb9a321
Revises: 1f641b5e3eae
Create Date: 2023-10-01 23:25:09.047977

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e11eecb9a321"
down_revision: Union[str, None] = "1f641b5e3eae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("price", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "price")
    # ### end Alembic commands ###
